<?php

/**
 * @file
 * Installation for Remote database roles.
 */

/**
 * Implements hook_uninstall().
 */
function remotedb_role_uninstall() {
  // Remove variables defined by this module.
  db_delete('variable')
    ->condition('name', 'remotedb_role_%_active', 'LIKE')
    ->execute();
  db_delete('variable')
    ->condition('name', 'remotedb_role_%_subscriptions', 'LIKE')
    ->execute();
  variable_del('remotedb_role_debug');
}
