<?php

/**
 * @file
 * Dummy module providing a mock class for remotedb_user entity.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\remotedbuser_test\Hook\RemotedbuserTestEntityHooks;

/**
 * Implements hook_entity_type_build().
 */
#[LegacyHook]
function remotedbuser_test_entity_type_build(array &$entity_types): void {
  \Drupal::service(RemotedbuserTestEntityHooks::class)->entityTypeBuild($entity_types);
}
