<?php

/**
 * @file
 * Dummy module providing a mock class for remotedb_user entity.
 */

use Drupal\remotedbuser_test\Entity\RemotedbUserStorage;

/**
 * Implements hook_entity_type_build().
 */
function remotedbuser_test_entity_type_build(array &$entity_types): void {
  if (isset($entity_types['remotedb_user'])) {
    $entity_types['remotedb_user']->setStorageClass(RemotedbUserStorage::class);
  }
}
