remotedb_role.settings:
  type: config_object
  label: 'Remote database role settings'
  mapping:
    remotedb:
      type: string
      label: 'Remote database'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: mapping
        mapping:
          status:
            type: boolean
            label: 'Status'
          subscriptions:
            type: sequence
            sequence:
              type: string
    debug:
      type: boolean
      label: 'Debug'
