<?php

/**
 * @file
 * Test module for setting a callback for the subscription service.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\remotedb_role_test\Hook\RemotedbRoleTestEntityHooks;

/**
 * Implements hook_ENTITY_TYPE_load() for 'remotedb'.
 */
#[LegacyHook]
function remotedb_role_test_remotedb_load(array $entities): void {
  \Drupal::service(RemotedbRoleTestEntityHooks::class)->remotedbLoad($entities);
}
