<?php

/**
 * @file
 * Enables order export via remote database.
 */

// ---------------------------------------------------------------------------
// DRUPAL HOOKS
// ---------------------------------------------------------------------------

/**
 * Implements hook_menu().
 * @return array
 */
function uc_remotedb_menu() {
  $items = array();

  // Add your menu items like this:
  $items['admin/config/system/remotedb/ubercart'] = array(
    'title' => 'Ubercart',
    'description' => 'Configurations for Ubercart',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_remotedb_settings'),
    'access arguments' => array('access RemoteDB administration page'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'uc_remotedb.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_cron().
 */
function uc_remotedb_cron() {
  // Decide if it's time to export orders.
  $time = strtotime(variable_get('uc_remotedb_order_export_freq', '1 day') . ' ago');
  if (variable_get('uc_remotedb_order_export_last', 0) < $time) {
    module_load_include('inc', 'uc_remotedb');
    $result = uc_remotedb_export_orders();
    drupal_set_message($result);
  }
}

// ---------------------------------------------------------------------------
// UBERCART HOOKS
// ---------------------------------------------------------------------------

/**
 * Implements hook_uc_order_load().
 */
function uc_remotedb_uc_order($op, $order) {
  if ($op == 'load') {
    $account = user_load($order->uid);
    if ($account) {
      $order->remotedb_uid = $account->remotedb_uid;
    }
  }
}

// ---------------------------------------------------------------------------
// ULTIMATE CRON HOOKS
// ---------------------------------------------------------------------------

/**
 * Implements hook_cronapi().
 *
 * As initiated by elysia_cron.
 * http://drupal.org/project/elysia_cron
 * */
function uc_remotedb_cronapi($op, $job = NULL) {
  switch ($op) {
    case 'list':
      return array(
        'uc_remotedb_export_orders' => t('Send orders to the remote database.'),
      );
    case 'rule':
      return '0 0 * * *';
    case 'execute':
      switch ($job) {
        case 'uc_remotedb_export_orders':
          module_load_include('inc', 'uc_remotedb');
          $result = uc_remotedb_export_orders();
          drupal_set_message($result);
          return $result;
      }
      break;
  }
}

/**
 * Implements hook_page_build().
 *
 * @param array $page
 *   The page variables.
 *
 * @return void
 *
function uc_remotedb_page_build(&$page) {
  $regex = '/admin\/store\/orders\/[0-9]+/';
  $q = $_GET['q'];
  if (preg_match($regex, $q) && !empty($page['content']['system_main']['customer']['pane'])) {
    $order_id = arg(3);
    $order = uc_order_load($order_id);
    $account = user_load($order->uid);
    print_r_tree(get_defined_vars());die();
    $afas_dbid = (empty($account->afas_dbid)) ? NULL : $account->afas_dbid;

    if ($afas_dbid) {
      // Add customer ID to customer pane.
      $page['content']['system_main']['customer']['pane']['afas_dbid'] = array(
        '#type' => 'item',
        '#title' => t('Afas Customer ID'),
        '#markup' => $afas_dbid,
      );
    }
  }
}*/
