<?php

/**
 * @file
 * Provides Single Sign-on functionality for remote users.
 */

use Drupal\remotedb_sso\Filter\SSO;
use Drupal\remotedb_sso\TicketServiceInterface;

// ---------------------------------------------------------------------------
// DRUPAL HOOKS
// ---------------------------------------------------------------------------

/**
 * Implements hook_menu().
 */
function remotedb_sso_menu() {
  $items = array();

  // Pass the user ID, timestamp, and hashed_pass.
  $items['sso/login/%/%/%'] = array(
    'title' => 'Login',
    'page callback' => 'remotedb_sso_login',
    'page arguments' => array(2, 3, 4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'remotedb_sso.pages.inc',
  );
  $items['sso/goto/%'] = array(
    'title' => 'SSO Redirect',
    'page callback' => 'remotedb_sso_goto',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'remotedb_sso.pages.inc',
  );

  $items['admin/config/services/remotedb/sso'] = array(
    'title' => 'SSO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('remotedb_sso_settings_form'),
    'access arguments' => array('access RemoteDB administration page'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'remotedb_sso.admin.inc',
  );

  return $items;
}

// ---------------------------------------------------------------------------
// FILTER
// ---------------------------------------------------------------------------

/**
 * Implements hook_filter_info().
 */
function remotedb_sso_filter_info() {
  $filters = array();
  $filters['remotedb_sso'] = array(
    'title' => t('SSO Link filter'),
    'description' => t('Automatically create SSO links from links to certain external websites'),
    'process callback' => 'remotedb_sso_filter_process',
    'settings callback' => 'remotedb_sso_filter_settings',
    'default settings' => array(
      'websites' => '',
    ),
    'tips callback' => 'remotedb_sso_filter_tips',
  );
  return $filters;
}

/**
 * Implements hook_filter_FILTER_tips().
 */
function remotedb_sso_filter_tips($filter, $format, $long = FALSE) {
  $sso_filter = new SSO($filter);
  return $sso_filter->tips($long);
}

/**
 * Filter process callback for remotedb_sso filter.
 *
 * Creates SSO links from links to certain external websites.
 *
 * @return string
 *   Text with generated SSO links.
 */
function remotedb_sso_filter_process($text, $filter, $format = NULL) {
  $sso_filter = new SSO($filter);
  return $sso_filter->process($text);
}

/**
 * Filter settings callback for remotedb_sso filter.
 */
function remotedb_sso_filter_settings($form, $form_state, $filter, $format, $defaults, $filters) {
  $filter->settings += $defaults;

  $sso_filter = new SSO($filter);
  return $sso_filter->settingsForm($form, $form_state);
}

// ---------------------------------------------------------------------------
// UTIL
// ---------------------------------------------------------------------------

/**
 * Gets ticket service to use.
 *
 * @return \Drupal\remotedb_sso\TicketServiceInterface | NULL
 *   An instance of TicketServiceInterface, if found.
 *   NULL otherwise.
 */
function remotedb_sso_get_ticket_service() {
  $remotedb = remotedbuser_get_remotedb();
  if ($remotedb) {
    $ticket_service_class = remotedb_sso_variable_get('ticket_service');
    $ticket_service = new $ticket_service_class($remotedb);
    if ($ticket_service instanceof TicketServiceInterface) {
      return $ticket_service;
    }
  }
  return NULL;
}

/**
 * Gets a remotedb_sso setting.
 *
 * @param string $name
 *   The setting to get.
 *
 * @return mixed
 *   The value of the setting.
 */
function remotedb_sso_variable_get($name) {
  $value = variable_get('remotedb_sso_' . $name, NULL);
  if (is_null($value)) {
    switch ($name) {
      case 'ticket_service':
        return 'Drupal\remotedb_sso\TicketService';
    }
  }
  return $value;
}
