<?php

/**
 * @file
 * Dummy module providing a mock class for remotedb entity.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\remotedb_test\Hook\RemotedbTestEntityHooks;

/**
 * Implements hook_entity_type_build().
 */
#[LegacyHook]
function remotedb_test_entity_type_build(array &$entity_types): void {
  \Drupal::service(RemotedbTestEntityHooks::class)->entityTypeBuild($entity_types);
}
