<?php

namespace Drupal\remotedb_sso\Controller;

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\Core\Url;
use Drupal\Core\Utility\Error;
use Drupal\remotedb\Exception\RemotedbException;
use Drupal\remotedb_sso\TicketServiceInterface;
use Drupal\remotedbuser\Entity\RemotedbUserInterface;
use Drupal\user\UserInterface;
use Drupal\user\UserStorageInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Controller for remotedb_sso routes.
 */
class SsoController extends ControllerBase {

  /**
   * The user storage.
   *
   * @var \Drupal\user\UserStorageInterface
   */
  protected $userStorage;

  /**
   * The service for requesting tickets from the remote database.
   *
   * @var \Drupal\remotedb_sso\TicketServiceInterface|null
   */
  protected $ticketService;

  /**
   * The remotedb logger channel.
   */
  protected LoggerInterface $logger;

  /**
   * Constructs a new SsoController object.
   *
   * @param \Drupal\Core\Session\AccountProxyInterface $current_user
   *   The current active user.
   * @param \Drupal\user\UserStorageInterface $user_storage
   *   The user storage.
   * @param \Psr\Log\LoggerInterface $logger
   *   The remotedb logger channel.
   * @param \Drupal\remotedb_sso\TicketServiceInterface $ticket_service
   *   (optional) The service for requesting tickets from the remote database.
   */
  public function __construct(AccountProxyInterface $current_user, UserStorageInterface $user_storage, LoggerInterface $logger, ?TicketServiceInterface $ticket_service = NULL) {
    $this->currentUser = $current_user;
    $this->userStorage = $user_storage;
    $this->logger = $logger;
    $this->ticketService = $ticket_service;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    try {
      $ticket_service = $container->get('remotedb_sso.ticket');
    }
    catch (RemotedbException $e) {
      // Log remotedb exceptions, but continue.
      $e->logError();
      $ticket_service = NULL;
    }

    return new static(
      $container->get('current_user'),
      $container->get('entity_type.manager')->getStorage('user'),
      $container->get('logger.factory')->get('remotedb'),
      $ticket_service
    );
  }

  /**
   * Logs in the specified user.
   *
   * @param \Symfony\Component\HttpFoundation\Request $request
   *   The request object.
   * @param int $remotedb_uid
   *   User ID from the central database.
   * @param int $timestamp
   *   Timestamp generated by the central database.
   * @param string $hashed_pass
   *   Hash generated by the central database.
   */
  public function login(Request $request, int $remotedb_uid, int $timestamp, string $hashed_pass): Response {
    $target_path = $request->query->get('target_path');
    $query = $request->query->all();
    unset($query['target_path']);

    $destination = Url::fromUserInput('/' . $target_path, [
      'query' => $query,
    ]);
    if ($destination->isRouted()) {
      $route_name = $destination->getRouteName();
      $route_parameters = $destination->getRouteParameters();
      $options = $destination->getOptions();
    }
    else {
      // Not a valid path. We will redirect to the front page later instead.
      $route_name = '<front>';
      $route_parameters = [];
      $options = [];
    }

    // Check if the ticket service is available.
    if (!$this->ticketService instanceof TicketServiceInterface) {
      // Ticket service is not available, so ignore the attempt and go to the
      // target url.
      return $this->redirect($route_name, $route_parameters, $options);
    }

    if ($this->currentUser->isAuthenticated()) {
      // A user is already logged in, so ignore the attempt and go to the
      // target url.
      return $this->redirect($route_name, $route_parameters, $options);
    }

    if ($remotedb_uid === 0) {
      // The user anonymous, so ignore the attempt and go to the target url.
      return $this->redirect($route_name, $route_parameters, $options);
    }

    // Validate the ticket.
    try {
      $remote_account = $this->ticketService->validateTicket($remotedb_uid, $timestamp, $hashed_pass);
      if ($remote_account instanceof RemotedbUserInterface) {
        // Ticket is valid. Update account data in local database.
        $account = $remote_account->toAccount();
        $account->save();
        $account_id = $account->id();
        if (!is_numeric($account_id)) {
          throw new \RuntimeException(sprintf('Failed to save account.'));
        }
        $account_id = (int) $account_id;

        // Reload the user's account object to ensure a full user object is
        // passed along to the various hooks.
        $this->userStorage->resetCache();
        $account = $this->userStorage->load($account_id);

        // Now login the user.
        if (!$account instanceof UserInterface) {
          throw new \RuntimeException(sprintf('Failed to load account %d.', $account_id));
        }
        user_login_finalize($account);
      }
    }
    catch (RemotedbException $e) {
      // Log any remote database exceptions.
      $e->logError();
    }
    catch (\Exception $e) {
      // Log any other exceptions.
      Error::logException($this->logger, $e);
    }

    // Finally, perform the redirect.
    return $this->redirect($route_name, $route_parameters, $options);
  }

  /**
   * Redirect the user to the website they wish to login at.
   *
   * @param \Symfony\Component\HttpFoundation\Request $request
   *   The http request.
   */
  public function goto(Request $request): Response {
    // Check if the ticket service is available.
    if (!$this->ticketService instanceof TicketServiceInterface) {
      throw new NotFoundHttpException();
    }

    // Get the site to go to.
    $site = $request->query->get('site');
    if (!is_string($site) || strlen(trim($site)) === 0) {
      throw new NotFoundHttpException();
    }

    // Get path, if there is one.
    $path = $request->query->get('path');

    // Check if the current user is authenticated.
    if ($this->currentUser->isAuthenticated()) {
      // Get ticket.
      $ticket = $this->ticketService->getTicket($this->currentUser);

      // Generate url to redirect to.
      $url_parts = [
        'http:/',
        $site,
        'sso/login',
        $ticket,
        $path,
      ];
    }
    else {
      // Not authenticated. Skip requesting a ticket. Instead redirect to the
      // plain url.
      $url_parts = [
        'http:/',
        $site,
        $path,
      ];
    }

    // Filter out empty parts.
    $url_parts = array_filter($url_parts);
    $url = implode('/', $url_parts);

    $response = new TrustedRedirectResponse($url, 307);
    $build = [
      '#cache' => [
        'max-age' => 0,
      ],
    ];
    $cache_metadata = CacheableMetadata::createFromRenderArray($build);
    $response->addCacheableDependency($cache_metadata);
    return $response;
  }

}
